# 应用信息(app info)
info:
  app:
    name: 上传组件
    description: 接收文件
    version: 1.0.0

# 日志相关配置(logging setting)
logging:
  path: E://logs//up2yun

spring:
  #数据库相关配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

# netty服务相关配置
netty:
  # servername
  name: UP2YUN-SERVER
  # 监听端口
  port: 8091
  # io线程数
  workerThreads: 20
  # 上传文件的的大小(100M)
  maxContentSize: 104857600
  # 上传文件保存用临时文件夹
  tempDir: E:/temp/up2yun/

#被通知人相关信息
notice:
  # 短信邮件转发服务器
  url: http://192.168.0.200:7080
  # 接收人列表
  emails: xieyushi@ancun.com
  # 一天允许短信通知最大次数
  maxSendTimes: 3
